name: Android CL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test CJDK (Java + C)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android NDK & CMake (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
          echo "NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3  # نسخه جدید

      - name: Grant execute permission for Gradle (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Java & C with Gradle (Linux/macOS)
        if: runner.os != 'Windows'
        run: ./gradlew assembleDebug

      - name: Build Java & C with Gradle (Windows)
        if: runner.os == 'Windows'
        run: gradlew.bat assembleDebug

      - name: Run Java Unit Tests
        run: ./gradlew test

      - name: Run Native C Tests (if available)
        run: |
          if [ -f "CMakeLists.txt" ]; then
            mkdir -p build && cd build
            cmake ..
            make
            ctest --output-on-failure
          else
            echo "No CMakeLists.txt found, skipping native tests."
          fi
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK & Native Libs
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            build/lib*.so
