name: Android CL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test Android Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Tests
        run: ./gradlew test

      - name: Lint Check
        run: ./gradlew lint

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
