name: Android CL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test CJDK (Java + C)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # جلوگیری از shallow clone

      - name: Fetch all history for proper Gradle execution
        run: git fetch --unshallow

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle (Linux/Mac)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Java & C with Gradle (Linux/Mac)
        if: runner.os != 'Windows'
        run: ./gradlew assembleDebug
        shell: bash

      - name: Build Java & C with Gradle (Windows)
        if: runner.os == 'Windows'
        run: gradlew.bat assembleDebug
        shell: cmd

      - name: Run Java Unit Tests (Linux/Mac)
        if: runner.os != 'Windows'
        run: ./gradlew test
        shell: bash

      - name: Run Java Unit Tests (Windows)
        if: runner.os == 'Windows'
        run: gradlew.bat test
        shell: cmd

      - name: Run Native C Tests (if available)
        run: |
          if [ -f "CMakeLists.txt" ]; then
            mkdir -p build && cd build
            cmake ..
            make
            ctest --output-on-failure
          else
            echo "No CMakeLists.txt found, skipping native tests."
          fi
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK & Native Libs
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            build/lib*.so
